name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "12 23 1 12/4 *"
    
permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: install shellcheck-sarif
        run: cargo install shellcheck-sarif
      
      - run: shellcheck -f json gh-oidc-sub | shellcheck-sarif | tee results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
